// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using VetiWebApplication.Data;

#nullable disable

namespace VetiWebApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260524192401_AddTratamento")]
    partial class AddTratamento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VetiWebApplication.Models.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DtConsulta")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("Notificar")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("TpEvento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("VeterinarioId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("VeterinarioId");

                    b.ToTable("TB_CONSULTA", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Exame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConsultaId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsDiagnostico")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsDocumento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime>("DtRealizacao")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaId");

                    b.ToTable("TB_EXAME", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.ExameMedicamento", b =>
                {
                    b.Property<int>("ExameId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("QtMedicamento")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ExameId", "MedicamentoId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("TB_EXAME_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Medicamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DsDosagem")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsFrequencia")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmMedicamento")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("TB_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Pet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DsEspecie")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsRaca")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmPet")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("NrIdade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("StCastrado")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("TutorId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("TB_PET", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Tratamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DsDiagnostico")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DsObservacao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DtInicio")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<string>("DtRetornoPrevisto")
                        .HasColumnType("NVARCHAR2(10)");

                    b.Property<int>("PetId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("TB_TRATAMENTO", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.TratamentoMedicamento", b =>
                {
                    b.Property<int>("TratamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("MedicamentoId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("DsInstrucao")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("QtMedicamento")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TratamentoId", "MedicamentoId");

                    b.HasIndex("MedicamentoId");

                    b.ToTable("TB_TRATAMENTO_MEDICAMENTO", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DsCpf")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("DsTelefone")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("NmTutor")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DsCpf")
                        .IsUnique();

                    b.HasIndex("DsEmail")
                        .IsUnique();

                    b.ToTable("TB_TUTOR", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Veterinario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DsEmail")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("DsPassword")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("DsEmail")
                        .IsUnique();

                    b.ToTable("TB_VETERINARIO", (string)null);
                });

            modelBuilder.Entity("VetiWebApplication.Models.Consulta", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Pet", "Pet")
                        .WithMany("Consultas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetiWebApplication.Models.Veterinario", "Veterinario")
                        .WithMany("Consultas")
                        .HasForeignKey("VeterinarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Veterinario");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Exame", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Consulta", "Consulta")
                        .WithMany("Exames")
                        .HasForeignKey("ConsultaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consulta");
                });

            modelBuilder.Entity("VetiWebApplication.Models.ExameMedicamento", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Exame", "Exame")
                        .WithMany("ExameMedicamentos")
                        .HasForeignKey("ExameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetiWebApplication.Models.Medicamento", "Medicamento")
                        .WithMany("ExameMedicamentos")
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exame");

                    b.Navigation("Medicamento");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Pet", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Tutor", "Tutor")
                        .WithMany("Pets")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Tratamento", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Pet", "Pet")
                        .WithMany()
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("VetiWebApplication.Models.TratamentoMedicamento", b =>
                {
                    b.HasOne("VetiWebApplication.Models.Medicamento", "Medicamento")
                        .WithMany()
                        .HasForeignKey("MedicamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VetiWebApplication.Models.Tratamento", "Tratamento")
                        .WithMany("TratamentoMedicamentos")
                        .HasForeignKey("TratamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Medicamento");

                    b.Navigation("Tratamento");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Consulta", b =>
                {
                    b.Navigation("Exames");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Exame", b =>
                {
                    b.Navigation("ExameMedicamentos");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Medicamento", b =>
                {
                    b.Navigation("ExameMedicamentos");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Pet", b =>
                {
                    b.Navigation("Consultas");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Tratamento", b =>
                {
                    b.Navigation("TratamentoMedicamentos");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Tutor", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("VetiWebApplication.Models.Veterinario", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
